# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/walleye/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    abl \
    apdp \
    cmnlib \
    cmnlib64 \
    devcfg \
    hyp \
    keymaster \
    modem \
    msadp \
    pmic \
    rpm \
    tz \
    xbl
